@baseUrl = http://localhost:3000
# # @name create_account
# POST {{baseUrl}}/accounts
# Content-Type: application/json

# {
#     "name": "Tiago Aeksio",
#     "email": "drazenkaAeksioVhaelor@gmail.com",
#     "password": "1234"
# }

# # @name authenticate
# POST {{baseUrl}}/sessions
# Content-Type: application/json

# {
#     "email": "drazenkaAeksioVhaelor@gmail.com",
#     "password": "1234"
# }

# # @name create_question
# POST {{baseUrl}}/questions
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkM2E1OGEzZi04MGNlLTRkMjUtOGM5NS02ZTQzYjI3MWU5ZWIiLCJpYXQiOjE3ODM0OTEwMzV9.dyWep_XIpiUtU1XaqZPCdGXJeoa3O9lRtMI_uyGizfR-D1uoXwigs91w6j0NF6Y5FpVow-Ci-dkZrcENAKOSq8q6N1HXC2-dLpAefO7iqWdrQyclOyJEFsT0AzMBc297OeLYhIDetrN7YBzgo-O7lXMqsKZgDOHmtR2GYw3Mko1kiLJPS9i3B4HHNVXOsqk1ADXc55YaFHhm4tnn47TkLshP9Wq-o2ToFm53E2vfoBzluVLQ4LEzGMl9mWuMzmm0T5gi5nmeJKfy2Zpv4SzwE7N4jhIDrKI6xyTGjCXV6rtvKXtoXTGo9po2LhpRUGKJkPiC7x_8WWXL2S9Uv4k87Q

# {
#     "title": "Nova pergunta drazenka",
#     "content":"Vhaelor o governante."
# }

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkM2E1OGEzZi04MGNlLTRkMjUtOGM5NS02ZTQzYjI3MWU5ZWIiLCJpYXQiOjE3ODM0OTEwMzV9.dyWep_XIpiUtU1XaqZPCdGXJeoa3O9lRtMI_uyGizfR-D1uoXwigs91w6j0NF6Y5FpVow-Ci-dkZrcENAKOSq8q6N1HXC2-dLpAefO7iqWdrQyclOyJEFsT0AzMBc297OeLYhIDetrN7YBzgo-O7lXMqsKZgDOHmtR2GYw3Mko1kiLJPS9i3B4HHNVXOsqk1ADXc55YaFHhm4tnn47TkLshP9Wq-o2ToFm53E2vfoBzluVLQ4LEzGMl9mWuMzmm0T5gi5nmeJKfy2Zpv4SzwE7N4jhIDrKI6xyTGjCXV6rtvKXtoXTGo9po2LhpRUGKJkPiC7x_8WWXL2S9Uv4k87Q
