@baseUrl = http://localhost:3000
//@authToken = {{authenticate.response.body.access_token}}

# # @name create_account
# POST {{baseUrl}}/accounts
# Content-Type: application/json

# {
#     "name": "Tiago oliveira",
#     "email": "tiago11deoliveira@gmail.com",
#     "password": "1234"
# }


# # @name authenticate
# POST {{baseUrl}}/sessions
# Content-Type: application/json

# {
#     "email": "tiago11deoliveira@gmail.com",
#     "password": "1234"
# }


# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MGJiNjdkNy05YTdjLTQ3ZjctODU3Ni0wYWFhYTI0YmM0NDIiLCJpYXQiOjE3NzMwOTIyNzR9.f5trDEBoJmTx_RyAxoO920jZrULmo_UxiWg9Lt8whc-iXqFyCo1i3qmbbfvAqhMrvowhUj2yiNN7WnY45G45RM232gKypjDdaqs7mnQonzAuNjAm96nA2_N-pnTH0ZPXyfAZNYKeUlNzjGVwwr55-7ZFrAmqC15j_5A2g1vmm_4lAffXPynYu2-8QiD4JQ79Fl9EoRT-2nCU9Wrh7JuVobgGjgARkxMyTwJyeqJzC7rUsWKktYQm4tUwUAlU5wPw55x7KRNT7Nsn6ApWG5BlyyA4J2WxKQPJ_D2Gw3ALUbb2rcojmogANL32iGc7gOfxJAc_pj0ycHKRbeoohK2gew